### ISSUE TITLE
Add hue, sharpness, backlight compensation and power line frequency compensation properties.

### ISSUE THREAD

**Issue by trcwm** [openpnp/openpnp-capture#24]
Add hue, sharpness, backlight compensation and power line frequency compensation properties.

**Comment by trcwm** [comment]
Fixed in upcoming v0.12 release.

**Comment by vonnieda** [comment]
Hi @trcwm, is this ready to be integrated into the Java stuff and released?

**Comment by trcwm** [comment]
Yes, I believe so!

**Comment by vonnieda** [comment]
Added and released. Thanks @trcwm!
