### ISSUE TITLE
Include linux-arm native binaries in release

### ISSUE THREAD

**Issue by darenschwenke** [openpnp/openpnp-capture#27]
I would really like to just host configuration files and not have to have my own copy of openpnp just for this, but as it stands the default instructions fail because linux-arm is not being included in the native binary releases.
I have them built locally, and probably just need a little help organizing things and pushing them up.

**Comment by brainstorm** [comment]
Should work now with aarch/arm64 @darenschwenke, see release:

https://github.com/openpnp/openpnp-capture/releases/tag/v0.0.19

Not if you wanted arm 32bits though :-S

**Comment by darenschwenke** [comment]
> Should work now with aarch/arm64 @darenschwenke, see release:
> 
> https://github.com/openpnp/openpnp-capture/releases/tag/v0.0.19
> 
> Not if you wanted arm 32bits though :-S

Thank you!
