### ISSUE TITLE
Binaries for Testing

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp-capture#3]
[openpnp-capture-test.zip](https://github.com/openpnp/openpnp-capture/files/1153564/openpnp-capture-test.zip)

**Comment by trcwm** [comment]
[OpenPnP_capture_win_17_7_2017.zip](https://github.com/openpnp/openpnp-capture/files/1154043/OpenPnP_capture_win_17_7_2017.zip)

**Comment by trcwm** [comment]
[openpnp-capture-win-17-7-2017-releasebuild.zip](https://github.com/openpnp/openpnp-capture/files/1154056/openpnp-capture-win-17-7-2017-releasebuild.zip)

**Comment by PeeJay** [comment]
Works with both of my webcams. One with exposure control, one without. Built on win64 using cmake to generate a vs2015 project file.

**Comment by trcwm** [comment]
[openpnp-capture-win-25-7-2017-releasebuild.zip](https://github.com/openpnp/openpnp-capture/files/1173846/openpnp-capture-win-25-7-2017-releasebuild.zip)

You might need to install the [Visual Studio 2013 redistributable package](https://www.microsoft.com/en-us/download/details.aspx?id=40784) for it to run.

**Comment by trcwm** [comment]
[openpnp-capture-win-1-8-2017-releasebuild.zip](https://github.com/openpnp/openpnp-capture/files/1190923/openpnp-capture-win-1-8-2017-releasebuild.zip)

Fixes: 
* Reports library version.
* Can now open raw RGB streams (Logitech C270).
* Supports zoom functionality.

You might need to install the [Visual Studio 2013 redistributable package](https://www.microsoft.com/en-us/download/details.aspx?id=40784) for it to run.

Please send feedback, screenshots, PPM captures, and/or text output dumps to: sofascener (email at sign here) gmail.com

**Comment by kakemoms** [comment]
I ran this with Visual Studio 2015 redistributable package installed.

The capture test program works with my 8MP chinese USB cam, but it has problems with the highest resolutions in MJPEG. Basically it lists all the IDs of the modes, but choosing anything above 2048 x 1536 just ends the program (see attachment - last part). For 2048 x 1536 it gives a slightly higher frame rate than what is given as supported (see attachment - first part). Not complaining about that one! ;-P

[openpnp-test.txt](https://github.com/openpnp/openpnp-capture/files/1254628/openpnp-test.txt)

**Comment by trcwm** [comment]
Thanks @kakemoms for running the test program and the report. 

The higher resolution mode fail with a '[ERR ] Error calling RenderStream (HRESULT=80004005)' which means 'Unknown error'. RenderStream is a windows internal function that takes care of the MJPEG decoding etc. I don't own a 8MP camera so it will be very difficult to find the cause of the problem. 

I will file an issue/bug report.
Regards,
Niels.

**Comment by kakemoms** [comment]
Ok. As noted I did install the Visual Studio 2015 redistributable package instead of the 2013 version. I will try to change to the 2013 version (if possible) and run things again. I may also try to install the 2017 version to see wether the error persists under that.

**Comment by PeeJay** [comment]
@kakemoms you will need to recompile the program to get it to work with different runtime versions.

**Comment by kakemoms** [comment]
(Y)

2017-08-28 14:35 GMT+02:00 Paul Jones <notifications@github.com>:

**Comment by PeeJay** [comment]
Long story short, the above attachment is hardcoded to use MSVCP120.dll and MSVCR120.dll
Here is one I made using VS2017, which uses the 2017 version of the runtime.
[Debug.zip](https://github.com/openpnp/openpnp-capture/files/1259824/Debug.zip)
