### ISSUE TITLE
Building for Windows with mingw64

### ISSUE THREAD

**Issue by ronaaron** [openpnp/openpnp-capture#39]
I'm trying to get the code compiled for Windows (64-bit, but that should make no difference) using the TDM mingw64 compiler.

Has anyone used the mingw compilers for this code?  It's not going very smoothly.

**Comment by ronaaron** [comment]
I was finally able to get it done. First I moved to makefiles instead of cmake; much easier to control things. Then I had to make some "#ifdef" additions.

If you're interested, I'll make a PR once I've got it all working as I'd like.

**Comment by trcwm** [comment]
Hi, 
What kind of errors were you getting with CMake?
