### ISSUE TITLE
Conflict with Qt Framework on macOS

### ISSUE THREAD

**Issue by grabusr** [openpnp/openpnp-capture#44]
Hi

When I use OpenPnp capture for capturing camera on some Mac laptops I receive the crash in Qt Event loop, sometimes even in provided example in repository. 
Crash happen in the Qt loop, after creating context by using `Cap_createContext()`.
Usually this is a information about double release of Cococa Event that causes the crash in debug mode.
My Setup:
MacBook Pro 2019, i7-8557U, macOS Catalina

**Comment by trcwm** [comment]
I don't have a Mac at the moment to debug this issue. @vonnieda have you seen this behavior in your setup?

**Comment by vonnieda** [comment]
I'm not able to reproduce. If it's still happening, please try running in a debugger and see if you can capture the error. Here's an example below:

```
DYLD_LIBRARY_PATH=../build lldb ./QtCaptureTest
(lldb) target create "./QtCaptureTest"
Current executable set to/QtCaptureTest' (x86_64).
```

```
Process 67202 stopped
Target 0: (QtCaptureTest) stopped.
```

```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x00007ff80155daba libsystem_kernel.dylib`mach_msg_trap + 10
    frame #15: 0x000000010002d4fe dyld`start + 462
```

```
(lldb) q
Quitting LLDB will kill one or more processes. Do you really want to proceed: [Y/n] y
>
```

**Comment by vonnieda** [comment]
Closing stale issue. Please see comment above and reopen if it's still happening.
