### ISSUE TITLE
📄 Documentation ?

### ISSUE THREAD

**Issue by Tanishq-Banyal** [openpnp/openpnp-capture#50]
Do you have any documentation ? Or some getting started guide ?

**Comment by trcwm** [comment]
Hi Tanishq-Banyal,

There is currently no documentation.

Take a look at QtCaptureTest or the win/tests linux/tests directories 
for examples how to use the library.
Note that the library was developed for OpenPnP and might not be 
suitable for the general case.

Regards,
Niels.

**Comment by vonnieda** [comment]
Added some basic documentation to https://github.com/openpnp/openpnp-capture#getting-started
