### ISSUE TITLE
openpnp-capture_Win32.dll v0.0.23 crashes 

### ISSUE THREAD

**Issue by calloatti** [openpnp/openpnp-capture#59]
Using openpnp-capture_Win32.dll v0.0.23 on WIndows 10, when calling Cap_openStream program crashes:

"Declare DLL call caused an exception."

Using  openpnp-capture_Win32.dll v0.0.22 the exact same code works with no issues.

I am using the C dll from Visual FoxPro.

**Comment by rlukasz** [comment]
Hi,
I noticed a similar issue with `openpnp-capture_x64.dll` v0.0.23 on Windows 11. Stream opens but it throws an exception at `Cap_closeStream` or `Cap_releaseContext`. I don't see this problem with v0.0.22.
Tested code: win/tests/main.cpp. Program exited with code -1073741819

**Comment by vonnieda** [comment]
This should be fixed in https://github.com/openpnp/openpnp-capture/releases/tag/v0.0.25. Please update and re-open if not.
