### ISSUE TITLE
YUV raw data required

### ISSUE THREAD

**Issue by chengjianwen** [openpnp/openpnp-capture#61]
most video compress using yuv2 as it's input format. or at least RGB2YUV2 function can be used.

**Comment by vonnieda** [comment]
Hi, can you give more detail please?

**Comment by chengjianwen** [comment]
I'm test an video encoder: libtheora, and it's need an yuv data.

**Comment by vonnieda** [comment]
Hi @chengjianwen - openpnp-capture returns frames in the format the camera format provides them in. No conversion is performed. So if your camera supports YUV or YUV2, you can select that format and receive frames. Any further conversion is up to you. The purpose of openpnp-capture is just to get frames from the camera.
