### ISSUE TITLE
An error is reported on windows 11

### ISSUE THREAD

**Issue by gbx666** [openpnp/openpnp-capture#64]
onecore\com\combase\objact\dllcache.cxx(2322)\combase.dll!00007FFE34ACCE67: (caller: 00007FFE34ACCCB8) ReturnHr(1) tid(72d4) 80040111 ClassFactory 无法供应请求的类
    Msg:[Error getting class object for CLSID ({860BB310-5D01-11D0-BD3B-00A0C911CE86}), IID ({00000001-0000-0000-C000-000000000046}) in DLL (C:\Windows\System32\devenum.dll)] 
onecore\com\combase\objact\dllcache.cxx(2327)\combase.dll!00007FFE34ACCCED: (caller: 00007FFE34ACCB38) ReturnHr(2) tid(72d4) 80040111 ClassFactory 无法供应请求的类
onecore\com\combase\objact\dllcache.hxx(2124)\combase.dll!00007FFE34ACCAEA: (caller: 00007FFE34ACC9CF) ReturnHr(3) tid(72d4) 80040111 ClassFactory 无法供应请求的类
onecore\com\combase\objact\dllcache.cxx(3093)\combase.dll!00007FFE34ACC9F7: (caller: 00007FFE34ACD98A) ReturnHr(4) tid(72d4) 80040111 ClassFactory 无法供应请求的类

**Comment by vonnieda** [comment]
Please add some more detail about the issue and re-open if still having this problem with the latest version.
